name: CI
on: [push]

jobs:
  build:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          path: .
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: |
          yarn install
          yarn tsc
          yarn eslint

  deploy:
    if: github.ref == 'refs/heads/main'
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          path: .
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Check out the source
        run: |
          yarn install
          yarn build
